# Generated by Django 3.1.7 on 2021-03-02 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20210302_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databeforeprocess',
            name='AudioFile',
        ),
    ]
